github: vorburger
patreon: vorburger
open_collective: vorburger
ko_fi: vorburger
tidelift: maven/ch.vorburger.mariaDB4j
community_bridge: MariaDB4j
liberapay: vorburger
issuehunt: vorburger
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: https://www.paypal.me/MichaelVorburgerCH
